import Dexie, { type EntityTable } from 'dexie';
export type Product={id:string;name:string;category:string;barcode?:string;unit:string;costPrice:number;sellingPrice:number;stock:number;minStock:number;sellable:boolean;active:boolean;isDemo?:boolean};
export type Customer={id:string;name:string;phone?:string;creditLimit:number;notes?:string;active?:boolean;isDemo?:boolean};
export type Staff={id:string;name:string;role:string;isDemo?:boolean};
export type SaleLine={productId:string;productName:string;quantity:number;unitPrice:number;unitCost:number;discount:number};
export type LocalSale={deviceTransactionId:string;customerId?:string;staffId:string;status:string;discount:number;occurredAt:string;deviceId:string;items:SaleLine[];payments:{method:string;amount:number}[];total:number;synced:boolean;isDemo?:boolean};
export type StockDraft={movementId:string;productId:string;staffId:string;type:string;quantityChange:number;notes?:string;deviceId:string};
export type Outbox={id?:number;type:'sale'|'customer'|'stock';payload:any;createdAt:string;attempts:number;lastError?:string};
class BarcodeDb extends Dexie{products!:EntityTable<Product,'id'>;customers!:EntityTable<Customer,'id'>;staff!:EntityTable<Staff,'id'>;sales!:EntityTable<LocalSale,'deviceTransactionId'>;outbox!:EntityTable<Outbox,'id'>;constructor(){super('thebarcode-pos');this.version(1).stores({products:'id,category,barcode,active',customers:'id,name,phone',staff:'id,name,role',sales:'deviceTransactionId,occurredAt,status,synced',outbox:'++id,type,createdAt'});this.version(2).stores({products:'id,category,barcode,active,isDemo',customers:'id,name,phone,isDemo',staff:'id,name,role,isDemo',sales:'deviceTransactionId,occurredAt,status,synced,isDemo',outbox:'++id,type,createdAt'});}}
export const db=new BarcodeDb();
export async function saveBootstrap(data:{products:Product[];customers:Customer[];staff:Staff[]}){await db.transaction('rw',db.products,db.customers,db.staff,async()=>{await db.products.bulkPut(data.products);await db.customers.bulkPut(data.customers);await db.staff.bulkPut(data.staff)});await seedLocalDemo(data)}
export async function queueSale(sale:LocalSale){await db.transaction('rw',db.sales,db.products,db.outbox,async()=>{await db.sales.put(sale);for(const line of sale.items){const product=await db.products.get(line.productId);if(product)await db.products.update(product.id,{stock:product.stock-line.quantity});}await db.outbox.add({type:'sale',payload:sale,createdAt:new Date().toISOString(),attempts:0});});}
export async function queueCustomer(customer:Customer){await db.transaction('rw',db.customers,db.outbox,async()=>{await db.customers.put(customer);await db.outbox.add({type:'customer',payload:customer,createdAt:new Date().toISOString(),attempts:0})});return customer}
export async function queueStockMovement(movement:StockDraft){await db.transaction('rw',db.products,db.outbox,async()=>{const product=await db.products.get(movement.productId);if(!product)throw new Error('Product not found');await db.products.update(product.id,{stock:Math.max(0,product.stock+movement.quantityChange)});await db.outbox.add({type:'stock',payload:movement,createdAt:new Date().toISOString(),attempts:0})});return movement}
async function seedLocalDemo(data:{products:Product[];customers:Customer[];staff:Staff[]}){if(await db.sales.where('isDemo').equals(1).count())return;const staff=data.staff.find(x=>x.isDemo),products=data.products.filter(x=>x.isDemo&&x.sellable);if(!staff||!products.length)return;const customer=data.customers.find(x=>x.isDemo&&x.name!=='Walk-in');const methods=['Cash','M-Pesa','Credit'];const rows=Array.from({length:18},(_,i)=>{const p=products[i%products.length],quantity=i%4===0?2:1,total=p.sellingPrice*quantity;return {deviceTransactionId:`demo-sale-${String(i+1).padStart(3,'0')}`,customerId:i%5===0?customer?.id:undefined,staffId:staff.id,status:i%5===0?'Credit':'Paid',discount:0,occurredAt:new Date(Date.now()-(17-i)*86400000).toISOString(),deviceId:'demo-device',items:[{productId:p.id,productName:p.name,quantity,unitPrice:p.sellingPrice,unitCost:p.costPrice,discount:0}],payments:[{method:methods[i%methods.length],amount:total}],total,synced:true,isDemo:true} satisfies LocalSale});await db.sales.bulkPut(rows)}
export async function removeLocalDemo(){await db.transaction('rw',db.products,db.customers,db.staff,db.sales,async()=>{await db.products.where('isDemo').equals(1).delete();await db.customers.where('isDemo').equals(1).delete();await db.staff.where('isDemo').equals(1).delete();await db.sales.where('isDemo').equals(1).delete()})}
