export type IndustryProfile={key:string;name:string;categories:string[];itemCategories:string[];productionLabel:string;inputLabel:string;productionHelp:string;defaultModules:string[]};
export const industryProfiles:IndustryProfile[]=[
 {key:"Hospitality",name:"Hospitality",categories:["BarCafe","Restaurant","Hotel","Catering"],itemCategories:["Beer","Spirits","Wine","Soft drinks","Coffee","Food","Kitchen supplies","Cleaning","Other"],productionLabel:"Recipes & preparation",inputLabel:"Ingredients / inputs",productionHelp:"Configure cocktails, meals, drinks and prepared items.",defaultModules:["sales","inventory","expenses","reports","accounting","ai","production"]},
 {key:"Bakery",name:"Bakery & food production",categories:["CakeShop","BreadBakery","PastryShop","CommercialBakery"],itemCategories:["Finished cakes","Bread","Pastries","Flour","Sugar","Dairy","Decorations","Packaging","Other"],productionLabel:"Recipes & production",inputLabel:"Ingredients",productionHelp:"Convert measured ingredients into finished bakery stock.",defaultModules:["sales","inventory","expenses","reports","accounting","ai","production"]},
 {key:"Retail",name:"Retail",categories:["GeneralRetail","Clothing","Electronics","Pharmacy","Hardware","Beauty","LeatherShop"],itemCategories:["Merchandise","Apparel","Accessories","Electronics","Consumables","Packaging","Returns","Other"],productionLabel:"Assemblies & bundles",inputLabel:"Components / items",productionHelp:"Create optional bundles or assembled products from stocked components.",defaultModules:["sales","inventory","expenses","reports","accounting","ai"]},
 {key:"Manufacturing",name:"Manufacturing",categories:["LightManufacturing","FoodProcessing","Textiles","LeatherGoods","Furniture"],itemCategories:["Raw materials","Components","Work in progress","Finished goods","Packaging","Waste","Consumables","Other"],productionLabel:"Bill of materials & production",inputLabel:"Materials / components",productionHelp:"Consume raw materials and components into finished goods.",defaultModules:["sales","inventory","expenses","reports","accounting","ai","production"]},
 {key:"Services",name:"Services",categories:["ProfessionalServices","SalonSpa","RepairWorkshop","Cleaning","Events"],itemCategories:["Services","Consumables","Spare parts","Equipment","Packages","Other"],productionLabel:"Service packages",inputLabel:"Resources / consumables",productionHelp:"Define optional service packages that consume stocked resources.",defaultModules:["sales","inventory","expenses","reports","accounting","ai"]},
 {key:"Wholesale",name:"Wholesale & distribution",categories:["WholesaleDistribution","BeverageDistribution","FoodDistribution"],itemCategories:["Wholesale goods","Cases","Packs","Returns","Damaged stock","Packaging","Other"],productionLabel:"Repacking & bundles",inputLabel:"Bulk inputs / components",productionHelp:"Track optional repacking and wholesale bundles.",defaultModules:["sales","inventory","expenses","reports","accounting","ai"]},
 {key:"Agriculture",name:"Agriculture",categories:["FarmInputs","Produce","Livestock"],itemCategories:["Produce","Inputs","Feed","Livestock","Packaging","Equipment","Other"],productionLabel:"Production & yields",inputLabel:"Inputs / materials",productionHelp:"Track optional input consumption and produced yields.",defaultModules:["sales","inventory","expenses","reports","accounting","ai","production"]},
 {key:"Other",name:"Other / custom",categories:["Custom"],itemCategories:["Products","Materials","Consumables","Services","Packaging","Other"],productionLabel:"Production & assemblies",inputLabel:"Inputs / materials",productionHelp:"Configure any item assembled or produced from other stock.",defaultModules:["sales","inventory","expenses","reports","accounting","ai"]}
];
export const profileFor=(key?:string)=>industryProfiles.find(x=>x.key===key)||industryProfiles[0];
export const categoryLabel=(value:string)=>value.replace(/([a-z])([A-Z])/g,"$1 $2");
export const enabledModules=(value?:string)=>new Set((value||"sales,inventory,expenses,reports,ai,production,accounting").split(',').map(x=>x.trim().toLowerCase()).filter(Boolean));
