export const APP_VERSION = import.meta.env.VITE_APP_VERSION || "1.8.5";
export const APP_CHANNEL = "local-windows";
export const RELEASE_NOTES = [
  "Owner-only verified local backup, purge and desktop restore controls",
  "Strict Demo and live institution data isolation across devices and analytics",
  "Authoritative approval and notification reconciliation with faster reports and insights",
  "Verified role-aware item CRUD with readable authorization and validation reasons",
  "Automatic dialog closing after successful transactional actions",
  "Green success and red failure messages with automatic dismissal",
  "Theme-aware branded login panel with Beyond Raw Data signoff",
  "Smaller Powered by Dukora | Beyond Raw Data receipt footer",
  "Persistent vertical or horizontal navigation layout",
  "Extra-large POS product cards with overlap-safe reflow",
  "Upgrade-safe local data storage with automatic daily backups",
  "Automatic held-bill workflow with explicit UNPAID, PAID and CREDIT printing",
  "Reliable multi-terminal held-bill revisions with new product additions",
  "Whole-unit sale quantities and governed paid or credit posting",
  "Attention counters and collapsible operations and setup navigation",
  "Projected stock alerts using recent posted-sale velocity",
  "Interactive notification center and low-stock restock drill-down",
  "Cross-terminal owner and manager approval queue for sensitive held-bill changes",
  "Validated bulk item upload with duplicate policies and safe batch reversal",
  "Unit-aware product variants for bottles, packs, weights, volumes and measured stock",
  "Three-decimal inventory quantities with separate package size and stock unit",
  "Governed held, paid, credit, partial-payment and refund bill lifecycle",
  "Interactive bill follow-up workspace with immutable revisions",
  "Live dashboard drill-downs and attention indicators",
  "Controlled item, customer and staff editing with archival",
  "Scrollable compact navigation and full-screen POS mode",
  "Persistent proportional POS display-size controls",
  "Elevated Xprinter driver installation and repair shortcut",
  "Offline x64 WebView2 runtime and resilient browser fallback",
  "Dukora Lite desktop edition with embedded SQLite storage",
  "Verified elevated Windows service setup and branded desktop launcher",
  "Live operational dashboards, expenses, reports and activity",
  "Smart Insights with local rules and optional server AI",
  "Rebranded as Dukora — Smarter Business Operations",
  "Shared organization, branch and terminal configuration",
  "Configurable 58/80 mm receipts and printing policies",
  "Native Windows and Docker deployment profiles",
  "Silent Xprinter XP-80 receipt printing",
  "Offline sales, customers and stock synchronization outbox",
  "Multi-terminal institution, outlet and device preparation",
];
