export const APP_VERSION = import.meta.env.VITE_APP_VERSION || "1.10.0";
export const APP_CHANNEL = "local-windows";
export const RELEASE_NOTES = [
  "Institution-level industry and business-category setup with persistent terminology and module choices",
  "Adaptive item categories and production language for hospitality, bakery, retail, manufacturing, services, wholesale and agriculture",
  "Core Sales, Inventory and Expenses kept enabled for accounting and stock integrity",
  "Complete expense editing for date, amount, method, supplier, tax, recurrence and archival with audit reasons",
  "Expense payment controls prevent settlement before approval or below amounts already paid",
  "Fixed SQLite expense-register reloads after saving, paying, approving or editing",
  "Saved expenses automatically clear stale filters and remain visible in the selected date range",
  "Pending approval and payment states are shown accurately in the expense register",
  "Open Preview module architecture with all completed features visible during local testing",
  "Version-controlled recipes with multiple ingredients, measured quantities and waste allowances",
  "Transactional production runs that consume ingredients, add finished stock and calculate weighted cost",
  "Production stock movements, history, permission controls and audit trail integration",
  "Approved-active expense governance for accurate dashboards and Smart Insights",
  "Permanent Keep held and start new control on Sell without receipt printing",
  "Reload and open controls for restarting or managing any held Sell order",
  "Separate Cash and M-Pesa paid-posting buttons with immediate paid-receipt printing",
  "Live sales collection rate replaces the hard-coded dashboard percentage",
  "Separate period-sales collection and actual cash-received measures across dashboard, reports, PDF and insights",
  "Persistent proportional Font & interface size settings across the complete application",
  "Controlled failed-order recovery with Retry, Open held bill and Start new order actions",
  "Stable draft transaction identity prevents duplicate bills when a response is lost",
  "Safe held-bill detachment keeps the record available without blocking the till",
  "Fixed the second-action 500 affecting held-bill save, print, paid and credit actions",
  "Transactional line replacement with explicit bill ownership and reload-tested persistence",
  "Authoritative held-bill revisions persisted before saving, posting or printing",
  "Cash and M-Pesa selection when revised held bills are posted as paid",
  "System messages displayed above every active dialog and workspace",
  "Product existence and stock validation before held-bill printing",
  "Offline WebView2 prerequisite detection and bundled installation for low-resource Windows targets",
  "Cashier and Storekeeper expense submission with Owner/Manager governance",
  "Stock-safe quantity ceilings across carts, held revisions and server posting",
  "Reliable item editing with custom-unit support and precise validation messages",
  "Printed unpaid bills detach safely into a fresh order with direct held-bill revision routing",
  "Production expense register with suppliers, references, due dates, tax and controlled settlement history",
  "Mark-as-read attention badges that reappear only when authoritative records change",
  "Owner-only verified local backup, purge and desktop restore controls",
  "Strict Demo and live institution data isolation across devices and analytics",
  "Authoritative approval and notification reconciliation with faster reports and insights",
  "Verified role-aware item CRUD with readable authorization and validation reasons",
  "Automatic dialog closing after successful transactional actions",
  "Green success and red failure messages with automatic dismissal",
  "Theme-aware branded login panel with Beyond Raw Data signoff",
  "Smaller Powered by Dukora | Beyond Raw Data receipt footer",
  "Persistent vertical or horizontal navigation layout",
  "Extra-large POS product cards with overlap-safe reflow",
  "Upgrade-safe local data storage with automatic daily backups",
  "Automatic held-bill workflow with explicit UNPAID, PAID and CREDIT printing",
  "Reliable multi-terminal held-bill revisions with new product additions",
  "Whole-unit sale quantities and governed paid or credit posting",
  "Attention counters and collapsible operations and setup navigation",
  "Projected stock alerts using recent posted-sale velocity",
  "Interactive notification center and low-stock restock drill-down",
  "Cross-terminal owner and manager approval queue for sensitive held-bill changes",
  "Validated bulk item upload with duplicate policies and safe batch reversal",
  "Unit-aware product variants for bottles, packs, weights, volumes and measured stock",
  "Three-decimal inventory quantities with separate package size and stock unit",
  "Governed held, paid, credit, partial-payment and refund bill lifecycle",
  "Interactive bill follow-up workspace with immutable revisions",
  "Live dashboard drill-downs and attention indicators",
  "Controlled item, customer and staff editing with archival",
  "Scrollable compact navigation and full-screen POS mode",
  "Persistent proportional POS display-size controls",
  "Elevated Xprinter driver installation and repair shortcut",
  "Offline x64 WebView2 runtime and resilient browser fallback",
  "Dukora Lite desktop edition with embedded SQLite storage",
  "Verified elevated Windows service setup and branded desktop launcher",
  "Live operational dashboards, expenses, reports and activity",
  "Smart Insights with local rules and optional server AI",
  "Rebranded as Dukora — Smarter Business Operations",
  "Shared organization, branch and terminal configuration",
  "Configurable 58/80 mm receipts and printing policies",
  "Native Windows and Docker deployment profiles",
  "Silent Xprinter XP-80 receipt printing",
  "Offline sales, customers and stock synchronization outbox",
  "Multi-terminal institution, outlet and device preparation",
];
