using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
namespace TheBarcode.Api;
public static class AccountingEndpoints
{
 public static void MapAccountingApi(this WebApplication app)
 {
  var api=app.MapGroup("/api/accounting").RequireAuthorization().RequireModule("accounting");
  api.MapGet("/accounts",async(AppDbContext db,ClaimsPrincipal p)=>await db.LedgerAccounts.AsNoTracking().Where(x=>x.IsDemo==Security.IsDemo(p)&&x.Active).OrderBy(x=>x.Code).ToListAsync());
  api.MapGet("/periods",async(AppDbContext db,ClaimsPrincipal p)=>await db.AccountingPeriods.AsNoTracking().Where(x=>x.IsDemo==Security.IsDemo(p)).OrderByDescending(x=>x.Start).ToListAsync());
  api.MapGet("/overview",async(DateOnly? from,DateOnly? to,AppDbContext db,ClaimsPrincipal p)=>{
   var demo=Security.IsDemo(p);var f=from??DateOnly.FromDateTime(DateTime.Today.AddDays(-29));var t=to??DateOnly.FromDateTime(DateTime.Today);if(t<f)(f,t)=(t,f);
   var sales=(await db.Sales.AsNoTracking().Include(x=>x.Items).Include(x=>x.Payments).Where(x=>x.IsDemo==demo&&x.Status!="Held"&&x.Status!="PendingApproval").ToListAsync()).Where(x=>DateOnly.FromDateTime(x.OccurredAt.LocalDateTime)>=f&&DateOnly.FromDateTime(x.OccurredAt.LocalDateTime)<=t).ToList();
   var expenses=await db.Expenses.AsNoTracking().Where(x=>x.IsDemo==demo&&x.Active&&x.Status=="Approved"&&x.Date>=f&&x.Date<=t).ToListAsync();var revenue=sales.Sum(x=>x.Total);var cost=sales.SelectMany(x=>x.Items).Sum(x=>x.UnitCost*x.Quantity);var expenseTotal=expenses.Sum(x=>x.Amount);var collected=sales.SelectMany(x=>x.Payments).Sum(x=>x.Amount);return Results.Ok(new{from=f,to=t,revenue,cost,grossProfit=revenue-cost,expenses=expenseTotal,netProfit=revenue-cost-expenseTotal,collected,receivables=Math.Max(0,revenue-collected),payables=expenses.Sum(x=>Math.Max(0,x.Amount-x.PaidAmount)),salesCount=sales.Count});
  }).RequireAuthorization(x=>x.RequireRole("Owner","Manager","Auditor"));
  api.MapGet("/trial-balance",async(DateOnly? from,DateOnly? to,AppDbContext db,ClaimsPrincipal p)=>{var demo=Security.IsDemo(p);var lines=await db.JournalLines.AsNoTracking().Join(db.JournalEntries.Where(x=>x.IsDemo==demo&&(from==null||x.Date>=from)&&(to==null||x.Date<=to)),l=>l.JournalEntryId,e=>e.Id,(l,e)=>l).ToListAsync();var accounts=await db.LedgerAccounts.AsNoTracking().Where(x=>x.IsDemo==demo&&x.Active).ToListAsync();return accounts.Select(a=>new{a.Code,a.Name,a.Type,debit=lines.Where(x=>x.AccountId==a.Id).Sum(x=>x.Debit),credit=lines.Where(x=>x.AccountId==a.Id).Sum(x=>x.Credit)}).Where(x=>x.debit!=0||x.credit!=0).OrderBy(x=>x.Code).ToList();}).RequireAuthorization(x=>x.RequireRole("Owner","Manager","Auditor"));
  api.MapGet("/journals",async(DateOnly? from,DateOnly? to,int? take,AppDbContext db,ClaimsPrincipal p)=>{var q=db.JournalEntries.AsNoTracking().Include(x=>x.Lines).Where(x=>x.IsDemo==Security.IsDemo(p));if(from is not null)q=q.Where(x=>x.Date>=from);if(to is not null)q=q.Where(x=>x.Date<=to);return Results.Ok(await q.OrderByDescending(x=>x.Date).ThenByDescending(x=>x.CreatedAt).Take(Math.Clamp(take??250,1,1000)).ToListAsync());}).RequireAuthorization(x=>x.RequireRole("Owner","Manager","Auditor"));
  api.MapPost("/adjustments",async(AdjustmentJournalRequest r,AppDbContext db,ClaimsPrincipal p)=>{if(r.Lines.Count<2||r.Lines.Any(x=>x.Debit<0||x.Credit<0)||Math.Round(r.Lines.Sum(x=>x.Debit)-r.Lines.Sum(x=>x.Credit),2)!=0)return Results.BadRequest(new{error="A journal must have at least two non-negative lines and balanced debits and credits"});var demo=Security.IsDemo(p);var ids=r.Lines.Select(x=>x.AccountId).Distinct().ToList();if(await db.LedgerAccounts.CountAsync(x=>ids.Contains(x.Id)&&x.IsDemo==demo&&x.Active)!=ids.Count)return Results.BadRequest(new{error="Every journal account must be active in this account"});if(await db.AccountingPeriods.AnyAsync(x=>x.IsDemo==demo&&x.Locked&&r.Date>=x.Start&&r.Date<=x.End))return Results.Conflict(new{error="The selected accounting period is locked"});var entry=new JournalEntry{Date=r.Date,SourceType="Adjustment",Memo=r.Memo.Trim(),IsDemo=demo};foreach(var l in r.Lines)entry.Lines.Add(new JournalLine{AccountId=l.AccountId,Description=l.Description?.Trim()??r.Memo.Trim(),Debit=Math.Round(l.Debit,2),Credit=Math.Round(l.Credit,2)});db.JournalEntries.Add(entry);db.AuditEvents.Add(new AuditEvent{StaffId=StaffId(p),Actor=p.Identity?.Name??"Staff",Action="Created",EntityType="JournalEntry",EntityId=entry.Id.ToString(),Details=$"Adjustment: {entry.Memo}"});await db.SaveChangesAsync();return Results.Created($"/api/accounting/journals/{entry.Id}",entry);}).RequireAuthorization(x=>x.RequireRole("Owner","Manager"));
  api.MapPost("/periods",async(AccountingPeriodRequest r,AppDbContext db,ClaimsPrincipal p)=>{if(r.End<r.Start||string.IsNullOrWhiteSpace(r.Name))return Results.BadRequest(new{error="Period name and valid dates are required"});var demo=Security.IsDemo(p);if(await db.AccountingPeriods.AnyAsync(x=>x.IsDemo==demo&&!((r.End<x.Start)||(r.Start>x.End))))return Results.Conflict(new{error="The period overlaps an existing period"});var period=new AccountingPeriod{Name=r.Name.Trim(),Start=r.Start,End=r.End,IsDemo=demo};db.AccountingPeriods.Add(period);await db.SaveChangesAsync();return Results.Created($"/api/accounting/periods/{period.Id}",period);}).RequireAuthorization(x=>x.RequireRole("Owner","Manager"));
  api.MapPut("/periods/{id:guid}/lock",async(Guid id,AppDbContext db,ClaimsPrincipal p)=>{var x=await db.AccountingPeriods.SingleOrDefaultAsync(x=>x.Id==id&&x.IsDemo==Security.IsDemo(p));if(x is null)return Results.NotFound();x.Locked=true;x.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync();return Results.Ok(x);}).RequireAuthorization(x=>x.RequireRole("Owner"));
 }
 static Guid StaffId(ClaimsPrincipal p)=>Guid.TryParse(p.FindFirst(ClaimTypes.NameIdentifier)?.Value,out var id)?id:throw new InvalidOperationException("Staff identity missing");
}
