using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace TheBarcode.Api;

public static class AdvancedInventoryEndpoints
{
    public static void MapAdvancedInventoryApi(this WebApplication app)
    {
        var api = app.MapGroup("/api").RequireAuthorization();
        var purchasing = api.MapGroup("/purchasing").RequireModule("inventory");
        purchasing.MapGet("/suppliers", async (AppDbContext db, ClaimsPrincipal p) =>
            await db.Suppliers.AsNoTracking().Where(x => x.IsDemo == Security.IsDemo(p) && x.Active).OrderBy(x => x.Name).ToListAsync());
        purchasing.MapPost("/suppliers", async (SupplierRequest r, AppDbContext db, ClaimsPrincipal p) =>
        {
            if (string.IsNullOrWhiteSpace(r.Name)) return Results.BadRequest(new { error = "Supplier name is required" });
            var demo = Security.IsDemo(p);
            var supplier = r.Id is Guid id ? await db.Suppliers.SingleOrDefaultAsync(x => x.Id == id && x.IsDemo == demo) : null;
            var action = supplier is null ? "Created" : "Updated";
            supplier ??= new Supplier { Name = r.Name.Trim(), IsDemo = demo };
            supplier.Name = r.Name.Trim(); supplier.Phone = r.Phone?.Trim(); supplier.Email = r.Email?.Trim(); supplier.TaxNumber = r.TaxNumber?.Trim(); supplier.Active = r.Active; supplier.UpdatedAt = DateTimeOffset.UtcNow;
            if (action == "Created") db.Suppliers.Add(supplier);
            db.AuditEvents.Add(Audit(p, action, "Supplier", supplier.Id, supplier.Name)); await db.SaveChangesAsync(); return Results.Ok(supplier);
        }).RequireAuthorization(x => x.RequireRole("Owner", "Manager", "Storekeeper"));
        purchasing.MapGet("/orders", async (AppDbContext db, ClaimsPrincipal p) =>
        {
            var demo = Security.IsDemo(p); var orders = (await db.PurchaseOrders.AsNoTracking().Include(x => x.Lines).Where(x => x.IsDemo == demo).Take(500).ToListAsync()).OrderByDescending(x => x.OrderedDate).ThenByDescending(x => x.CreatedAt).ToList();
            var suppliers = await db.Suppliers.AsNoTracking().Where(x => x.IsDemo == demo).ToDictionaryAsync(x => x.Id, x => x.Name);
            var products = await db.Products.AsNoTracking().Where(x => x.IsDemo == demo).ToDictionaryAsync(x => x.Id, x => x.Name);
            return Results.Ok(orders.Select(o => new { o.Id, o.Number, o.SupplierId, supplierName = suppliers.GetValueOrDefault(o.SupplierId, "Unknown supplier"), o.Status, o.OrderedDate, o.ExpectedDate, o.Notes, o.Total, lines = o.Lines.Select(l => new { l.Id, l.ProductId, productName = products.GetValueOrDefault(l.ProductId, "Unknown item"), l.QuantityOrdered, l.QuantityReceived, l.UnitCost, l.LineTotal }) }));
        });
        purchasing.MapPost("/orders", async (PurchaseOrderRequest r, AppDbContext db, ClaimsPrincipal p) =>
        {
            if (r.Lines.Count == 0 || r.Lines.Any(x => x.Quantity <= 0 || x.UnitCost < 0)) return Results.BadRequest(new { error = "Add at least one item with a positive quantity and valid cost" });
            var demo = Security.IsDemo(p); if (!await db.Suppliers.AnyAsync(x => x.Id == r.SupplierId && x.IsDemo == demo && x.Active)) return Results.BadRequest(new { error = "Select an active supplier" });
            var ids = r.Lines.Select(x => x.ProductId).Distinct().ToList(); var products = await db.Products.Where(x => ids.Contains(x.Id) && x.IsDemo == demo && x.Active).ToDictionaryAsync(x => x.Id); if (products.Count != ids.Count) return Results.BadRequest(new { error = "Every purchase item must be active in this account" });
            var order = r.Id is Guid id ? await db.PurchaseOrders.Include(x => x.Lines).SingleOrDefaultAsync(x => x.Id == id && x.IsDemo == demo) : null; var action = order is null ? "Created" : "Updated";
            if (order is not null && order.Status is not "Draft") return Results.Conflict(new { error = "Only draft purchase orders can be edited" });
            order ??= new PurchaseOrder { IsDemo = demo, StaffId = StaffId(p), Number = $"PO-{DateTime.UtcNow:yyyyMMdd-HHmmss}" };
            order.SupplierId = r.SupplierId; order.BranchId = r.BranchId; order.OrderedDate = r.OrderedDate; order.ExpectedDate = r.ExpectedDate; order.Notes = r.Notes?.Trim(); order.Total = r.Lines.Sum(x => x.Quantity * x.UnitCost); order.UpdatedAt = DateTimeOffset.UtcNow;
            if (order.Lines.Count > 0) db.PurchaseOrderLines.RemoveRange(order.Lines); order.Lines.Clear(); foreach (var line in r.Lines) order.Lines.Add(new PurchaseOrderLine { ProductId = line.ProductId, QuantityOrdered = line.Quantity, UnitCost = Math.Round(line.UnitCost, 2), LineTotal = Math.Round(line.Quantity * line.UnitCost, 2) });
            if (action == "Created") db.PurchaseOrders.Add(order); db.AuditEvents.Add(Audit(p, action, "PurchaseOrder", order.Id, $"{order.Number}; total {order.Total:0.00}")); await db.SaveChangesAsync(); return Results.Ok(order);
        }).RequireAuthorization(x => x.RequireRole("Owner", "Manager", "Storekeeper"));
        purchasing.MapPost("/orders/{id:guid}/send", async (Guid id, AppDbContext db, ClaimsPrincipal p) => { var o = await db.PurchaseOrders.SingleOrDefaultAsync(x => x.Id == id && x.IsDemo == Security.IsDemo(p)); if (o is null) return Results.NotFound(); if (o.Status != "Draft") return Results.Conflict(new { error = "Only draft purchase orders can be sent" }); o.Status = "Ordered"; o.UpdatedAt = DateTimeOffset.UtcNow; db.AuditEvents.Add(Audit(p, "Sent", "PurchaseOrder", id, o.Number)); await db.SaveChangesAsync(); return Results.Ok(o); }).RequireAuthorization(x => x.RequireRole("Owner", "Manager", "Storekeeper"));
        purchasing.MapPost("/orders/{id:guid}/receive", async (Guid id, ReceivePurchaseRequest r, AppDbContext db, ClaimsPrincipal p) =>
        {
            var demo = Security.IsDemo(p); var order = await db.PurchaseOrders.Include(x => x.Lines).SingleOrDefaultAsync(x => x.Id == id && x.IsDemo == demo); if (order is null) return Results.NotFound(); if (order.Status is "Cancelled" or "Received") return Results.Conflict(new { error = "This purchase order is already closed" });
            var lineIds = r.Lines.Select(x => x.LineId).ToList(); var lines = order.Lines.Where(x => lineIds.Contains(x.Id)).ToDictionary(x => x.Id); if (lines.Count != lineIds.Count) return Results.BadRequest(new { error = "One or more receipt lines do not belong to this order" });
            var products = await db.Products.Where(x => lines.Values.Select(l => l.ProductId).Contains(x.Id) && x.IsDemo == demo).ToDictionaryAsync(x => x.Id); await using var tx = await db.Database.BeginTransactionAsync();
            foreach (var received in r.Lines) { if (received.Quantity <= 0) return Results.BadRequest(new { error = "Received quantity must be positive" }); var line = lines[received.LineId]; var remaining = line.QuantityOrdered - line.QuantityReceived; if (received.Quantity > remaining) return Results.BadRequest(new { error = $"Cannot receive more than the remaining {remaining:0.###} units" }); var product = products[line.ProductId]; var cost = Math.Round(received.UnitCost ?? line.UnitCost, 2); var oldStock = product.Stock; var newStock = oldStock + received.Quantity; product.CostPrice = newStock <= 0 ? cost : Math.Round((oldStock * product.CostPrice + received.Quantity * cost) / newStock, 2); product.Stock = newStock; line.QuantityReceived += received.Quantity; line.UpdatedAt = DateTimeOffset.UtcNow; db.StockMovements.Add(new StockMovement { ProductId = product.Id, StaffId = StaffId(p), Type = "Purchase receipt", QuantityChange = received.Quantity, Notes = $"{order.Number}: {r.Notes}".Trim(), OccurredAt = DateTimeOffset.UtcNow }); if (!string.IsNullOrWhiteSpace(received.LotNumber)) { var lot = await db.StockLots.SingleOrDefaultAsync(x => x.ProductId == product.Id && x.IsDemo == demo && x.LotNumber == received.LotNumber); var newLot = lot is null; lot ??= new StockLot { ProductId = product.Id, SupplierId = order.SupplierId, LotNumber = received.LotNumber.Trim(), IsDemo = demo }; lot.Quantity += received.Quantity; lot.UnitCost = cost; lot.ExpiryDate = received.ExpiryDate; lot.UpdatedAt = DateTimeOffset.UtcNow; if (newLot) db.StockLots.Add(lot); } }
            order.Status = order.Lines.All(x => x.QuantityReceived >= x.QuantityOrdered) ? "Received" : "PartiallyReceived"; order.UpdatedAt = DateTimeOffset.UtcNow; db.AuditEvents.Add(Audit(p, "Received", "PurchaseOrder", id, $"{order.Number}; {r.Lines.Count} lines", r.DeviceId)); await db.SaveChangesAsync(); await tx.CommitAsync(); return Results.Ok(order);
        }).RequireAuthorization(x => x.RequireRole("Owner", "Manager", "Storekeeper"));

        var stock = api.MapGroup("/stock").RequireModule("inventory");
        stock.MapPost("/wastage", async (WastageRequest r, AppDbContext db, ClaimsPrincipal p) => { if (r.Quantity <= 0 || string.IsNullOrWhiteSpace(r.Reason)) return Results.BadRequest(new { error = "Positive wastage quantity and a reason are required" }); var demo = Security.IsDemo(p); var product = await db.Products.SingleOrDefaultAsync(x => x.Id == r.ProductId && x.IsDemo == demo && x.Active); if (product is null) return Results.NotFound(); if (r.Quantity > product.Stock) return Results.Conflict(new { error = $"Cannot waste more than the available {product.Stock:0.###} units" }); if (!string.IsNullOrWhiteSpace(r.LotNumber)) { var lot = await db.StockLots.SingleOrDefaultAsync(x => x.ProductId == product.Id && x.IsDemo == demo && x.LotNumber == r.LotNumber); if (lot is null || lot.Quantity < r.Quantity) return Results.Conflict(new { error = "The selected lot does not contain enough stock" }); lot.Quantity -= r.Quantity; lot.UpdatedAt = DateTimeOffset.UtcNow; } product.Stock -= r.Quantity; var movement = new StockMovement { ProductId = product.Id, StaffId = StaffId(p), Type = "Wastage", QuantityChange = -r.Quantity, Notes = $"{r.Reason.Trim()}" + (string.IsNullOrWhiteSpace(r.LotNumber) ? "" : $" · Lot {r.LotNumber.Trim()}"), OccurredAt = DateTimeOffset.UtcNow }; db.StockMovements.Add(movement); db.AuditEvents.Add(Audit(p, "Recorded", "Wastage", movement.Id, $"{product.Name}: {r.Quantity:0.###} · {r.Reason.Trim()}", r.DeviceId)); await db.SaveChangesAsync(); return Results.Ok(new { movement, stock = product.Stock }); }).RequireAuthorization(x => x.RequireRole("Owner", "Manager", "Storekeeper"));
        stock.MapGet("/lots", async (Guid? productId, AppDbContext db, ClaimsPrincipal p) => { var q = db.StockLots.AsNoTracking().Where(x => x.IsDemo == Security.IsDemo(p) && x.Quantity > 0); if (productId is not null) q = q.Where(x => x.ProductId == productId); var rows = await q.OrderBy(x => x.ExpiryDate).ThenBy(x => x.LotNumber).Take(1000).ToListAsync(); return Results.Ok(rows); });
        stock.MapGet("/expiring", async (int? days, AppDbContext db, ClaimsPrincipal p) => { var until = DateOnly.FromDateTime(DateTime.Today.AddDays(Math.Clamp(days ?? 30, 1, 365))); return Results.Ok(await db.StockLots.AsNoTracking().Where(x => x.IsDemo == Security.IsDemo(p) && x.Quantity > 0 && x.ExpiryDate != null && x.ExpiryDate <= until).OrderBy(x => x.ExpiryDate).ToListAsync()); });
        stock.MapGet("/stocktakes", async (AppDbContext db, ClaimsPrincipal p) => { var demo = Security.IsDemo(p); var rows = (await db.StocktakeSessions.AsNoTracking().Include(x => x.Lines).Where(x => x.IsDemo == demo).Take(250).ToListAsync()).OrderByDescending(x => x.CountDate).ThenByDescending(x => x.CreatedAt).ToList(); return Results.Ok(rows); });
        stock.MapPost("/stocktakes", async (StocktakeRequest r, AppDbContext db, ClaimsPrincipal p) => { if (string.IsNullOrWhiteSpace(r.Name) || r.Lines.Count == 0 || r.Lines.Any(x => x.CountedQuantity < 0)) return Results.BadRequest(new { error = "Name and non-negative counted quantities are required" }); var demo = Security.IsDemo(p); var ids = r.Lines.Select(x => x.ProductId).Distinct().ToList(); var products = await db.Products.Where(x => ids.Contains(x.Id) && x.IsDemo == demo && x.Active).ToDictionaryAsync(x => x.Id); if (products.Count != ids.Count) return Results.BadRequest(new { error = "Every counted item must be active in this account" }); var session = r.Id is Guid id ? await db.StocktakeSessions.Include(x => x.Lines).SingleOrDefaultAsync(x => x.Id == id && x.IsDemo == demo) : null; if (session is not null && session.Status != "Open") return Results.Conflict(new { error = "Only open stocktakes can be edited" }); var action = session is null ? "Created" : "Updated"; session ??= new StocktakeSession { Name = r.Name.Trim(), StaffId = StaffId(p), CountDate = r.CountDate, IsDemo = demo }; session.Name = r.Name.Trim(); session.CountDate = r.CountDate; if (session.Lines.Count > 0) db.StocktakeLines.RemoveRange(session.Lines); session.Lines.Clear(); foreach (var line in r.Lines) { var expected = products[line.ProductId].Stock; session.Lines.Add(new StocktakeLine { ProductId = line.ProductId, ExpectedQuantity = expected, CountedQuantity = line.CountedQuantity, Variance = line.CountedQuantity - expected, LotNumber = line.LotNumber?.Trim(), ExpiryDate = line.ExpiryDate, Notes = line.Notes?.Trim() }); } if (action == "Created") db.StocktakeSessions.Add(session); db.AuditEvents.Add(Audit(p, action, "Stocktake", session.Id, session.Name)); await db.SaveChangesAsync(); return Results.Ok(session); }).RequireAuthorization(x => x.RequireRole("Owner", "Manager", "Storekeeper"));
        stock.MapPost("/stocktakes/{id:guid}/submit", async (Guid id, AppDbContext db, ClaimsPrincipal p) => { var x = await db.StocktakeSessions.SingleOrDefaultAsync(x => x.Id == id && x.IsDemo == Security.IsDemo(p)); if (x is null) return Results.NotFound(); if (x.Status != "Open") return Results.Conflict(new { error = "Only open stocktakes can be submitted" }); x.Status = "Submitted"; x.SubmittedAt = DateTimeOffset.UtcNow; x.UpdatedAt = DateTimeOffset.UtcNow; db.AuditEvents.Add(Audit(p, "Submitted", "Stocktake", id, x.Name)); await db.SaveChangesAsync(); return Results.Ok(x); }).RequireAuthorization(x => x.RequireRole("Owner", "Manager", "Storekeeper"));
        stock.MapPost("/stocktakes/{id:guid}/approve", async (Guid id, StocktakeApprovalRequest r, AppDbContext db, ClaimsPrincipal p) => { var demo = Security.IsDemo(p); var x = await db.StocktakeSessions.Include(x => x.Lines).SingleOrDefaultAsync(x => x.Id == id && x.IsDemo == demo); if (x is null) return Results.NotFound(); if (x.Status != "Submitted") return Results.Conflict(new { error = "Only submitted stocktakes can be approved" }); if (!r.Approve) { x.Status = "Rejected"; x.UpdatedAt = DateTimeOffset.UtcNow; db.AuditEvents.Add(Audit(p, "Rejected", "Stocktake", id, r.Reason ?? "Rejected")); await db.SaveChangesAsync(); return Results.Ok(x); } var ids = x.Lines.Select(l => l.ProductId).Distinct().ToList(); var products = await db.Products.Where(p => ids.Contains(p.Id) && p.IsDemo == demo).ToDictionaryAsync(p => p.Id); await using var tx = await db.Database.BeginTransactionAsync(); foreach (var line in x.Lines) { var product = products[line.ProductId]; var delta = line.CountedQuantity - product.Stock; if (delta != 0) { product.Stock = Math.Max(0, line.CountedQuantity); db.StockMovements.Add(new StockMovement { ProductId = product.Id, StaffId = StaffId(p), Type = "Stocktake adjustment", QuantityChange = delta, Notes = $"{x.Name}: {r.Reason}".Trim(), OccurredAt = DateTimeOffset.UtcNow }); } if (!string.IsNullOrWhiteSpace(line.LotNumber)) { var lot = await db.StockLots.SingleOrDefaultAsync(l => l.ProductId == product.Id && l.IsDemo == demo && l.LotNumber == line.LotNumber); var newLot = lot is null; lot ??= new StockLot { ProductId = product.Id, LotNumber = line.LotNumber.Trim(), IsDemo = demo }; lot.Quantity = line.CountedQuantity; lot.ExpiryDate = line.ExpiryDate; lot.UpdatedAt = DateTimeOffset.UtcNow; if (newLot) db.StockLots.Add(lot); } } x.Status = "Approved"; x.ApprovedAt = DateTimeOffset.UtcNow; x.UpdatedAt = DateTimeOffset.UtcNow; db.AuditEvents.Add(Audit(p, "Approved", "Stocktake", id, x.Name, r.DeviceId)); await db.SaveChangesAsync(); await tx.CommitAsync(); return Results.Ok(x); }).RequireAuthorization(x => x.RequireRole("Owner", "Manager"));
    }

    static Guid StaffId(ClaimsPrincipal p) => Guid.TryParse(p.FindFirst(ClaimTypes.NameIdentifier)?.Value, out var id) ? id : throw new InvalidOperationException("Staff identity missing");
    static AuditEvent Audit(ClaimsPrincipal p, string action, string type, Guid id, string details, string? device = null) => new() { StaffId = StaffId(p), Actor = p.Identity?.Name ?? "Staff", Action = action, EntityType = type, EntityId = id.ToString(), Details = details, DeviceId = device };
}
