using Microsoft.EntityFrameworkCore;
namespace TheBarcode.Api;
public static class DemoData
{
 public const string UserName="Demo User";public const string Pin="123456";
 public static async Task Ensure(AppDbContext db){if(!await db.Staff.AnyAsync(x=>x.IsDemo))db.Staff.Add(new StaffUser{Name=UserName,Role="Cashier",PinHash=Security.HashPin(Pin),IsDemo=true});if(!await db.Products.AnyAsync(x=>x.IsDemo))db.Products.AddRange(new[]{P("Tusker Lager","Beer",230,320,38,18),P("White Cap","Beer",250,350,24,18),P("Guinness","Beer",285,380,16,18),P("Heineken","Beer",310,420,9,12),P("Chrome","Spirits",170,260,42,30),P("Jameson","Spirits",2850,3800,6,5),P("Smirnoff","Spirits",1180,1700,18,8),P("Alvaro","Soft drinks",95,160,31,20),P("Cappuccino","Coffee",95,280,30,15),P("Beef Burger","Food",280,650,22,12),P("Margherita Pizza","Food",310,720,14,8),P("Fresh Milk","Kitchen",110,0,12,8,false)});if(!await db.Customers.AnyAsync(x=>x.IsDemo))db.Customers.AddRange(new[]{C("Walk-in",null,0),C("Brian Otieno","254712345678",5000),C("Mercy Njeri","254798111222",8000),C("David Kamau","254722445566",12000),C("Amina Hassan","254733778899",6000)});if(!await db.Expenses.AnyAsync(x=>x.IsDemo))db.Expenses.AddRange(new Expense{Date=DateOnly.FromDateTime(DateTime.Today),Category="Inventory",Description="Supplier delivery",Amount=8200,PaidAmount=8200,Method="M-Pesa",IsDemo=true},new Expense{Date=DateOnly.FromDateTime(DateTime.Today.AddDays(-1)),Category="Utilities",Description="Electricity tokens",Amount=1500,PaidAmount=1500,Method="M-Pesa",IsDemo=true},new Expense{Date=DateOnly.FromDateTime(DateTime.Today.AddDays(-2)),Category="Maintenance",Description="Fridge repair",Amount=3200,PaidAmount=0,Method="Pending",IsDemo=true});await db.SaveChangesAsync();}
 public static async Task Remove(AppDbContext db){db.Expenses.RemoveRange(await db.Expenses.Where(x=>x.IsDemo).ToListAsync());db.Customers.RemoveRange(await db.Customers.Where(x=>x.IsDemo).ToListAsync());db.Products.RemoveRange(await db.Products.Where(x=>x.IsDemo).ToListAsync());db.Staff.RemoveRange(await db.Staff.Where(x=>x.IsDemo).ToListAsync());await db.SaveChangesAsync();}
 static Product P(string n,string c,decimal cost,decimal sell,decimal stock,decimal min,bool sellable=true)=>new(){Name=n,Category=c,Unit=c=="Food"?"serving":"item",CostPrice=cost,SellingPrice=sell,Stock=stock,MinStock=min,Sellable=sellable,IsDemo=true};static Customer C(string n,string? phone,decimal limit)=>new(){Name=n,Phone=phone,CreditLimit=limit,Notes="Demo record",IsDemo=true};
}
