namespace TheBarcode.Api;
public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class StaffUser : Entity { public required string Name { get; set; } public required string PinHash { get; set; } public required string Role { get; set; } public bool Active { get; set; } = true; public bool IsDemo { get; set; } }
public sealed class Product : Entity { public required string Name { get; set; } public required string Category { get; set; } public string? Barcode { get; set; } public string Unit { get; set; } = "item"; public decimal CostPrice { get; set; } public decimal SellingPrice { get; set; } public decimal Stock { get; set; } public decimal MinStock { get; set; } public bool Sellable { get; set; } = true; public bool Active { get; set; } = true; public bool IsDemo { get; set; } }
public sealed class Customer : Entity { public required string Name { get; set; } public string? Phone { get; set; } public decimal CreditLimit { get; set; } public string? Notes { get; set; } public bool IsDemo { get; set; } }
public sealed class Sale : Entity { public required string DeviceTransactionId { get; set; } public long ReceiptNumber { get; set; } public Guid? CustomerId { get; set; } public Guid StaffId { get; set; } public string Status { get; set; } = "Paid"; public decimal Discount { get; set; } public decimal Total { get; set; } public DateTimeOffset OccurredAt { get; set; } public List<SaleItem> Items { get; set; } = []; public List<Payment> Payments { get; set; } = []; }
public sealed class SaleItem : Entity { public Guid SaleId { get; set; } public Guid ProductId { get; set; } public required string ProductName { get; set; } public decimal Quantity { get; set; } public decimal UnitPrice { get; set; } public decimal UnitCost { get; set; } public decimal Discount { get; set; } }
public sealed class Payment : Entity { public Guid SaleId { get; set; } public required string Method { get; set; } public decimal Amount { get; set; } public DateTimeOffset PaidAt { get; set; } }
public sealed class StockMovement : Entity { public Guid ProductId { get; set; } public Guid StaffId { get; set; } public required string Type { get; set; } public decimal QuantityChange { get; set; } public string? Notes { get; set; } public DateTimeOffset OccurredAt { get; set; } }
public sealed class Expense : Entity { public DateOnly Date { get; set; } public required string Category { get; set; } public required string Description { get; set; } public decimal Amount { get; set; } public decimal PaidAmount { get; set; } public required string Method { get; set; } public bool IsDemo { get; set; } }
public sealed class AuditEvent : Entity { public Guid? StaffId { get; set; } public required string Actor { get; set; } public required string Action { get; set; } public required string EntityType { get; set; } public string? EntityId { get; set; } public required string Details { get; set; } public string? DeviceId { get; set; } public DateTimeOffset OccurredAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class OrganizationProfile : Entity { public required string Name { get; set; } public string? LegalName { get; set; } public string IndustryProfile { get; set; } = "BarCafe"; public string Currency { get; set; } = "KES"; public string? Phone { get; set; } public string? Email { get; set; } public string? Address { get; set; } public string? TaxPin { get; set; } public string? VatNumber { get; set; } public string? Tagline { get; set; } }
public sealed class Branch : Entity { public string Name { get; set; } = ""; public string Code { get; set; } = "MAIN"; public string? Address { get; set; } public string? Phone { get; set; } public bool Active { get; set; } = true; }
public sealed class Terminal : Entity { public Guid BranchId { get; set; } public string Name { get; set; } = ""; public string DeviceKey { get; set; } = ""; public bool Active { get; set; } = true; }
public sealed class ReceiptConfiguration : Entity { public int PaperWidthMm { get; set; } = 80; public bool ShowBusinessDetails { get; set; } = true; public bool ShowCustomer { get; set; } = true; public bool ShowCashier { get; set; } = true; public bool ShowTax { get; set; } public bool ShowCustomerBalance { get; set; } = true; public bool ShowPoweredBy { get; set; } = true; public bool AutoPrintPaidSale { get; set; } public string CreditSalePrintMode { get; set; } = "Optional"; public string PaymentReceiptPrintMode { get; set; } = "Optional"; public int Copies { get; set; } = 1; public string Footer { get; set; } = "Thank you for your business."; public string ReceiptPrefix { get; set; } = "RCP"; public string InvoicePrefix { get; set; } = "INV"; public string PaymentPrefix { get; set; } = "PAY"; }
public record LoginRequest(Guid StaffId, string Pin); public record StaffRequest(string Name, string Pin, string Role); public record CustomerRequest(Guid? Id, string Name, string? Phone, decimal CreditLimit, string? Notes); public record ProductRequest(string Name, string Category, string? Barcode, string Unit, decimal CostPrice, decimal SellingPrice, decimal Stock, decimal MinStock, bool Sellable); public record StockRequest(Guid MovementId, Guid ProductId, Guid StaffId, string Type, decimal QuantityChange, string? Notes, string? DeviceId); public record SaleLineRequest(Guid ProductId, decimal Quantity, decimal UnitPrice, decimal Discount); public record PaymentRequest(string Method, decimal Amount); public record SaleRequest(string DeviceTransactionId, Guid? CustomerId, Guid StaffId, string Status, decimal Discount, DateTimeOffset OccurredAt, string? DeviceId, List<SaleLineRequest> Items, List<PaymentRequest> Payments); public record ExpenseRequest(DateOnly Date, string Category, string Description, decimal Amount, decimal PaidAmount, string Method, Guid StaffId, string? DeviceId);
public record OrganizationRequest(string Name,string? LegalName,string IndustryProfile,string Currency,string? Phone,string? Email,string? Address,string? TaxPin,string? VatNumber,string? Tagline);
public record BranchRequest(Guid? Id,string Name,string Code,string? Address,string? Phone,bool Active);
public record TerminalRequest(Guid? Id,Guid BranchId,string Name,string DeviceKey,bool Active);
public record ReceiptConfigurationRequest(int PaperWidthMm,bool ShowBusinessDetails,bool ShowCustomer,bool ShowCashier,bool ShowTax,bool ShowCustomerBalance,bool ShowPoweredBy,bool AutoPrintPaidSale,string CreditSalePrintMode,string PaymentReceiptPrintMode,int Copies,string Footer,string ReceiptPrefix,string InvoicePrefix,string PaymentPrefix);
