namespace TheBarcode.Api;
public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class StaffUser : Entity { public required string Name { get; set; } public required string PinHash { get; set; } public required string Role { get; set; } public string Permissions { get; set; } = ""; public bool Active { get; set; } = true; public bool IsDemo { get; set; } }
public sealed class Product : Entity { public required string Name { get; set; } public required string Category { get; set; } public string? Brand { get; set; } public string? Barcode { get; set; } public string Unit { get; set; } = "item"; public decimal PackageQuantity { get; set; } = 1; public string PackageUnit { get; set; } = "item"; public string TrackingMode { get; set; } = "Discrete"; public string? Supplier { get; set; } public decimal TaxRate { get; set; } public decimal CostPrice { get; set; } public decimal SellingPrice { get; set; } public decimal Stock { get; set; } public decimal MinStock { get; set; } public bool Sellable { get; set; } = true; public bool Active { get; set; } = true; public bool IsDemo { get; set; } }
public sealed class Customer : Entity { public required string Name { get; set; } public string? Phone { get; set; } public decimal CreditLimit { get; set; } public string? Notes { get; set; } public bool Active { get; set; } = true; public bool IsDemo { get; set; } }
public sealed class Sale : Entity { public required string DeviceTransactionId { get; set; } public long ReceiptNumber { get; set; } public int DailyOrderNumber { get; set; } public int? WalkInNumber { get; set; } public Guid? CustomerId { get; set; } public Guid StaffId { get; set; } public string Status { get; set; } = "Paid"; public decimal Discount { get; set; } public decimal Total { get; set; } public DateTimeOffset OccurredAt { get; set; } public DateTimeOffset? DueAt { get; set; } public DateTimeOffset? PostedAt { get; set; } public int Revision { get; set; } = 1; public string? Notes { get; set; } public bool IsDemo { get; set; } public List<SaleItem> Items { get; set; } = []; public List<Payment> Payments { get; set; } = []; public List<BillRevision> Revisions { get; set; } = []; }
public sealed class BillRevision : Entity { public Guid SaleId { get; set; } public int Revision { get; set; } public Guid StaffId { get; set; } public string Action { get; set; } = "Updated"; public string Reason { get; set; } = ""; public string SnapshotJson { get; set; } = "{}"; }
public sealed class SaleItem : Entity { public Guid SaleId { get; set; } public Guid ProductId { get; set; } public required string ProductName { get; set; } public decimal Quantity { get; set; } public decimal UnitPrice { get; set; } public decimal UnitCost { get; set; } public decimal Discount { get; set; } }
public sealed class Payment : Entity { public Guid SaleId { get; set; } public required string Method { get; set; } public decimal Amount { get; set; } public DateTimeOffset PaidAt { get; set; } }
public sealed class StockMovement : Entity { public Guid ProductId { get; set; } public Guid StaffId { get; set; } public required string Type { get; set; } public decimal QuantityChange { get; set; } public string? Notes { get; set; } public DateTimeOffset OccurredAt { get; set; } }
public sealed class ProductImportBatch : Entity { public Guid StaffId { get; set; } public required string DuplicatePolicy { get; set; } public int TotalRows { get; set; } public int CreatedCount { get; set; } public int UpdatedCount { get; set; } public int SkippedCount { get; set; } public string Status { get; set; } = "Completed"; public string? DeviceId { get; set; } public List<ProductImportLine> Lines { get; set; } = []; }
public sealed class ProductImportLine : Entity { public Guid ProductImportBatchId { get; set; } public Guid ProductId { get; set; } public bool ProductWasCreated { get; set; } public decimal StockChange { get; set; } public string? PreviousJson { get; set; } }
public sealed class Expense : Entity { public DateOnly Date { get; set; } public required string Category { get; set; } public required string Description { get; set; } public decimal Amount { get; set; } public decimal PaidAmount { get; set; } public required string Method { get; set; } public string? Payee { get; set; } public string? Reference { get; set; } public DateOnly? DueDate { get; set; } public decimal TaxAmount { get; set; } public string? Notes { get; set; } public bool Recurring { get; set; } public string Status { get; set; } = "Approved"; public Guid? BranchId { get; set; } public bool Active { get; set; } = true; public bool IsDemo { get; set; } public List<ExpensePayment> Payments { get; set; } = []; }
public sealed class ExpensePayment : Entity { public Guid ExpenseId { get; set; } public decimal Amount { get; set; } public required string Method { get; set; } public string? Reference { get; set; } public string? Notes { get; set; } public Guid StaffId { get; set; } public DateTimeOffset PaidAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class AuditEvent : Entity { public Guid? StaffId { get; set; } public required string Actor { get; set; } public required string Action { get; set; } public required string EntityType { get; set; } public string? EntityId { get; set; } public required string Details { get; set; } public string? DeviceId { get; set; } public DateTimeOffset OccurredAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class OrganizationProfile : Entity { public required string Name { get; set; } public string? LegalName { get; set; } public string IndustryProfile { get; set; } = "Hospitality"; public string BusinessCategory { get; set; } = "BarCafe"; public string EnabledModules { get; set; } = "sales,inventory,expenses,reports,ai,production"; public bool ProfileConfigured { get; set; } public string Currency { get; set; } = "KES"; public string? Phone { get; set; } public string? Email { get; set; } public string? Address { get; set; } public string? TaxPin { get; set; } public string? VatNumber { get; set; } public string? Tagline { get; set; } }
public sealed class Branch : Entity { public string Name { get; set; } = ""; public string Code { get; set; } = "MAIN"; public string? Address { get; set; } public string? Phone { get; set; } public bool Active { get; set; } = true; }
public sealed class Terminal : Entity { public Guid BranchId { get; set; } public string Name { get; set; } = ""; public string DeviceKey { get; set; } = ""; public bool Active { get; set; } = true; }
public sealed class ReceiptConfiguration : Entity { public int PaperWidthMm { get; set; } = 80; public bool ShowBusinessDetails { get; set; } = true; public bool ShowCustomer { get; set; } = true; public bool ShowCashier { get; set; } = true; public bool ShowTax { get; set; } public bool ShowCustomerBalance { get; set; } = true; public bool ShowPoweredBy { get; set; } = true; public bool AutoPrintPaidSale { get; set; } public string CreditSalePrintMode { get; set; } = "Optional"; public string PaymentReceiptPrintMode { get; set; } = "Optional"; public int Copies { get; set; } = 1; public string Footer { get; set; } = "Thank you for your business."; public string ReceiptPrefix { get; set; } = "RCP"; public string InvoicePrefix { get; set; } = "INV"; public string PaymentPrefix { get; set; } = "PAY"; }
public sealed class InsightsConfiguration : Entity { public bool Enabled { get; set; } public string Endpoint { get; set; } = "https://api.openai.com/v1/chat/completions"; public string Model { get; set; } = "gpt-5-mini"; public string? EncryptedApiKey { get; set; } public bool AllowUserNames { get; set; } }
public record LoginRequest(Guid StaffId, string Pin); public record StaffRequest(string Name, string Pin, string Role); public record CustomerRequest(Guid? Id, string Name, string? Phone, decimal CreditLimit, string? Notes); public record ProductRequest(string Name, string Category, string? Barcode, string Unit, decimal CostPrice, decimal SellingPrice, decimal Stock, decimal MinStock, bool Sellable, string? Brand=null, decimal PackageQuantity=1, string? PackageUnit=null, string TrackingMode="Discrete", string? Supplier=null, decimal TaxRate=0); public record StockRequest(Guid MovementId, Guid ProductId, Guid StaffId, string Type, decimal QuantityChange, string? Notes, string? DeviceId); public record SaleLineRequest(Guid ProductId, decimal Quantity, decimal UnitPrice, decimal Discount); public record PaymentRequest(string Method, decimal Amount); public record SaleRequest(string DeviceTransactionId, Guid? CustomerId, Guid StaffId, string Status, decimal Discount, DateTimeOffset OccurredAt, string? DeviceId, List<SaleLineRequest> Items, List<PaymentRequest> Payments); public record ExpenseRequest(DateOnly Date, string Category, string Description, decimal Amount, decimal PaidAmount, string Method, Guid StaffId, string? DeviceId);
public record OrganizationRequest(string Name,string? LegalName,string IndustryProfile,string Currency,string? Phone,string? Email,string? Address,string? TaxPin,string? VatNumber,string? Tagline);
public record BranchRequest(Guid? Id,string Name,string Code,string? Address,string? Phone,bool Active);
public record TerminalRequest(Guid? Id,Guid BranchId,string Name,string DeviceKey,bool Active);
public record ReceiptConfigurationRequest(int PaperWidthMm,bool ShowBusinessDetails,bool ShowCustomer,bool ShowCashier,bool ShowTax,bool ShowCustomerBalance,bool ShowPoweredBy,bool AutoPrintPaidSale,string CreditSalePrintMode,string PaymentReceiptPrintMode,int Copies,string Footer,string ReceiptPrefix,string InvoicePrefix,string PaymentPrefix);
public record BillLineRequest(Guid ProductId,decimal Quantity,decimal UnitPrice,decimal Discount);
public record HoldBillRequest(string DeviceTransactionId,Guid? CustomerId,Guid StaffId,decimal Discount,string? Notes,string? DeviceId,List<BillLineRequest> Items);
public record UpdateBillRequest(Guid? CustomerId,decimal Discount,string? Notes,string Reason,string? DeviceId,int ExpectedRevision,List<BillLineRequest> Items);
public record ResolveBillApprovalRequest(bool Approve,string Reason,string? DeviceId);
public record PostBillRequest(string Status,string Method,decimal AmountPaid,DateTimeOffset? DueAt,string? Notes,string? DeviceId);
public record BillPaymentRequest(string Method,decimal Amount,string? Reference,string? DeviceId);
public record PaymentMethodUpdateRequest(string Method,string Reason,string? DeviceId);
public record ProductUpdateRequest(string Name,string Category,string? Barcode,string Unit,decimal CostPrice,decimal SellingPrice,decimal MinStock,bool Sellable,bool Active,string Reason,string? Brand=null,decimal PackageQuantity=1,string? PackageUnit=null,string TrackingMode="Discrete",string? Supplier=null,decimal TaxRate=0);
public record CustomerUpdateRequest(string Name,string? Phone,decimal CreditLimit,string? Notes,bool Active,string Reason);
public record StaffUpdateRequest(string Name,string Role,bool Active,string? NewPin,string Reason,string? Permissions=null);
public record PermissionUpdateRequest(string? Permissions,string Reason);
public record InsightsSettingsRequest(bool Enabled,string Endpoint,string Model,string? ApiKey,bool ClearApiKey,bool AllowUserNames);
public record ProductionExpenseRequest(DateOnly Date,string Category,string Description,decimal Amount,decimal InitiallyPaid,string Method,string? Payee,string? Reference,DateOnly? DueDate,decimal TaxAmount,string? Notes,bool Recurring,Guid? BranchId,string? DeviceId);
public record ExpensePaymentRequest(decimal Amount,string Method,string? Reference,string? Notes,string? DeviceId);
public record ExpenseUpdateRequest(DateOnly Date,string Category,string Description,decimal Amount,string Method,string? Payee,string? Reference,DateOnly? DueDate,decimal TaxAmount,string? Notes,bool Recurring,bool Active,string Reason);
public sealed class Recipe : Entity { public Guid ProductId { get; set; } public string Name { get; set; } = ""; public decimal YieldQuantity { get; set; } = 1; public int Version { get; set; } = 1; public bool Active { get; set; } = true; public string? Notes { get; set; } public bool IsDemo { get; set; } public List<RecipeIngredient> Ingredients { get; set; } = []; }
public sealed class RecipeIngredient : Entity { public Guid RecipeId { get; set; } public Guid IngredientProductId { get; set; } public decimal Quantity { get; set; } public decimal WastePercent { get; set; } }
public sealed class ProductionRun : Entity { public Guid RecipeId { get; set; } public Guid ProductId { get; set; } public Guid StaffId { get; set; } public decimal QuantityProduced { get; set; } public decimal TotalCost { get; set; } public string Status { get; set; } = "Completed"; public string? Notes { get; set; } public DateTimeOffset OccurredAt { get; set; } = DateTimeOffset.UtcNow; public bool IsDemo { get; set; } }
public sealed class LedgerAccount : Entity { public required string Code { get; set; } public required string Name { get; set; } public required string Type { get; set; } public bool System { get; set; } public bool Active { get; set; } = true; public bool IsDemo { get; set; } }
public sealed class JournalEntry : Entity { public DateOnly Date { get; set; } public required string SourceType { get; set; } public string? SourceId { get; set; } public required string Memo { get; set; } public string Status { get; set; } = "Posted"; public bool IsDemo { get; set; } public List<JournalLine> Lines { get; set; } = []; }
public sealed class JournalLine : Entity { public Guid JournalEntryId { get; set; } public Guid AccountId { get; set; } public required string Description { get; set; } public decimal Debit { get; set; } public decimal Credit { get; set; } }
public sealed class AccountingPeriod : Entity { public required string Name { get; set; } public DateOnly Start { get; set; } public DateOnly End { get; set; } public bool Locked { get; set; } public bool IsDemo { get; set; } }
public sealed class Supplier : Entity { public required string Name { get; set; } public string? Phone { get; set; } public string? Email { get; set; } public string? TaxNumber { get; set; } public bool Active { get; set; } = true; public bool IsDemo { get; set; } }
public sealed class PurchaseOrder : Entity { public required string Number { get; set; } public Guid SupplierId { get; set; } public Guid StaffId { get; set; } public Guid? BranchId { get; set; } public string Status { get; set; } = "Draft"; public DateOnly OrderedDate { get; set; } public DateOnly? ExpectedDate { get; set; } public string? Notes { get; set; } public decimal Total { get; set; } public bool IsDemo { get; set; } public List<PurchaseOrderLine> Lines { get; set; } = []; }
public sealed class PurchaseOrderLine : Entity { public Guid PurchaseOrderId { get; set; } public Guid ProductId { get; set; } public decimal QuantityOrdered { get; set; } public decimal QuantityReceived { get; set; } public decimal UnitCost { get; set; } public decimal LineTotal { get; set; } }
public sealed class StockLot : Entity { public Guid ProductId { get; set; } public Guid? SupplierId { get; set; } public string LotNumber { get; set; } = ""; public DateOnly? ExpiryDate { get; set; } public decimal Quantity { get; set; } public decimal UnitCost { get; set; } public bool IsDemo { get; set; } }
public sealed class StocktakeSession : Entity { public required string Name { get; set; } public Guid StaffId { get; set; } public string Status { get; set; } = "Open"; public DateOnly CountDate { get; set; } public DateTimeOffset? SubmittedAt { get; set; } public DateTimeOffset? ApprovedAt { get; set; } public bool IsDemo { get; set; } public List<StocktakeLine> Lines { get; set; } = []; }
public sealed class StocktakeLine : Entity { public Guid StocktakeSessionId { get; set; } public Guid ProductId { get; set; } public decimal ExpectedQuantity { get; set; } public decimal CountedQuantity { get; set; } public decimal Variance { get; set; } public string? LotNumber { get; set; } public DateOnly? ExpiryDate { get; set; } public string? Notes { get; set; } }
public record LedgerAccountRequest(string Code,string Name,string Type);
public record AccountingPeriodRequest(string Name,DateOnly Start,DateOnly End);
public record AdjustmentJournalRequest(DateOnly Date,string Memo,List<AdjustmentLineRequest> Lines);
public record AdjustmentLineRequest(Guid AccountId,decimal Debit,decimal Credit,string? Description);
public record RecipeIngredientRequest(Guid ProductId,decimal Quantity,decimal WastePercent);
public record RecipeRequest(Guid ProductId,string Name,decimal YieldQuantity,string? Notes,List<RecipeIngredientRequest> Ingredients);
public record ProductionRunRequest(Guid RecipeId,decimal Quantity,string? Notes,string? DeviceId);
public record IndustryConfigurationRequest(string IndustryProfile,string BusinessCategory,List<string> EnabledModules);
public record SupplierRequest(Guid? Id,string Name,string? Phone,string? Email,string? TaxNumber,bool Active);
public record SupplierDeleteRequest(string? Reason);
public record PurchaseOrderLineRequest(Guid ProductId,decimal Quantity,decimal UnitCost);
public record PurchaseOrderRequest(Guid? Id,Guid SupplierId,Guid? BranchId,DateOnly OrderedDate,DateOnly? ExpectedDate,string? Notes,List<PurchaseOrderLineRequest> Lines);
public record ReceivePurchaseRequest(List<ReceivePurchaseLineRequest> Lines,string? Notes,string? DeviceId);
public record ReceivePurchaseLineRequest(Guid LineId,decimal Quantity,decimal? UnitCost,string? LotNumber,DateOnly? ExpiryDate);
public record StocktakeLineRequest(Guid ProductId,decimal CountedQuantity,string? LotNumber,DateOnly? ExpiryDate,string? Notes);
public record StocktakeRequest(Guid? Id,string Name,DateOnly CountDate,List<StocktakeLineRequest> Lines);
public record StocktakeApprovalRequest(bool Approve,string? Reason,string? DeviceId);
public record WastageRequest(Guid ProductId,decimal Quantity,string? LotNumber,string Reason,string? DeviceId);
