using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
namespace TheBarcode.Api;
public static class IndustryProfileEndpoints
{
 static readonly string[] Modules=["sales","inventory","expenses","reports","ai","production","accounting"];
 static readonly Dictionary<string,string[]> Categories=new(StringComparer.OrdinalIgnoreCase){["Hospitality"]=["BarCafe","Restaurant","Hotel","Catering"],["Bakery"]=["CakeShop","BreadBakery","PastryShop","CommercialBakery"],["Retail"]=["GeneralRetail","Clothing","Electronics","Pharmacy","Hardware","Beauty","LeatherShop"],["Manufacturing"]=["LightManufacturing","FoodProcessing","Textiles","LeatherGoods","Furniture"],["Services"]=["ProfessionalServices","SalonSpa","RepairWorkshop","Cleaning","Events"],["Wholesale"]=["WholesaleDistribution","BeverageDistribution","FoodDistribution"],["Agriculture"]=["FarmInputs","Produce","Livestock"],["Other"]=["Custom"]};
 public static void MapIndustryProfileApi(this WebApplication app){var api=app.MapGroup("/api/settings").RequireAuthorization();api.MapGet("/industry-catalog",()=>Results.Ok(new{industries=Categories.Select(x=>new{key=x.Key,name=x.Key,categories=x.Value}),modules=new[]{new{key="sales",name="Sales & POS"},new{key="inventory",name="Inventory"},new{key="expenses",name="Expenses"},new{key="reports",name="Reports"},new{key="accounting",name="Accounting"},new{key="ai",name="Smart Insights"},new{key="production",name="Production / assemblies"}}}));api.MapPut("/industry",async(IndustryConfigurationRequest r,AppDbContext db,ClaimsPrincipal p)=>{if(!Categories.TryGetValue(r.IndustryProfile,out var categories)||!categories.Contains(r.BusinessCategory,StringComparer.OrdinalIgnoreCase))return Results.BadRequest(new{error="Choose a valid industry and business category"});var enabled=r.EnabledModules.Intersect(Modules,StringComparer.OrdinalIgnoreCase).Distinct(StringComparer.OrdinalIgnoreCase).ToList();foreach(var required in new[]{"sales","inventory","expenses"})if(!enabled.Contains(required,StringComparer.OrdinalIgnoreCase))enabled.Add(required);var org=await db.Organizations.OrderBy(x=>x.Id).FirstAsync();org.IndustryProfile=r.IndustryProfile;org.BusinessCategory=r.BusinessCategory;org.EnabledModules=string.Join(',',enabled);org.ProfileConfigured=true;org.UpdatedAt=DateTimeOffset.UtcNow;db.AuditEvents.Add(new AuditEvent{StaffId=Guid.TryParse(p.FindFirst(ClaimTypes.NameIdentifier)?.Value,out var id)?id:null,Actor=p.Identity?.Name??"Staff",Action="Updated",EntityType="IndustryProfile",EntityId=org.Id.ToString(),Details=$"{org.IndustryProfile} · {org.BusinessCategory} · {org.EnabledModules}",DeviceId="settings"});await db.SaveChangesAsync();return Results.Ok(org);}).RequireAuthorization(x=>x.RequireRole("Owner"));}
}
