using Microsoft.EntityFrameworkCore;
namespace TheBarcode.Api;
public static class SeedData
{
 public static async Task Initialize(AppDbContext db,string bootstrapPin){await db.Database.EnsureCreatedAsync();if(db.Database.IsNpgsql())foreach(var statement in new[]{"ALTER TABLE staff ADD COLUMN IF NOT EXISTS is_demo boolean NOT NULL DEFAULT false","ALTER TABLE products ADD COLUMN IF NOT EXISTS is_demo boolean NOT NULL DEFAULT false","ALTER TABLE customers ADD COLUMN IF NOT EXISTS is_demo boolean NOT NULL DEFAULT false","ALTER TABLE expenses ADD COLUMN IF NOT EXISTS is_demo boolean NOT NULL DEFAULT false",
 "CREATE TABLE IF NOT EXISTS organizations (id uuid PRIMARY KEY,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,name text NOT NULL,legal_name text NULL,industry_profile text NOT NULL,currency text NOT NULL,phone text NULL,email text NULL,address text NULL,tax_pin text NULL,vat_number text NULL,tagline text NULL)",
 "CREATE TABLE IF NOT EXISTS branches (id uuid PRIMARY KEY,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,name text NOT NULL,code text NOT NULL,address text NULL,phone text NULL,active boolean NOT NULL)",
 "CREATE UNIQUE INDEX IF NOT EXISTS ix_branches_code ON branches(code)",
 "CREATE TABLE IF NOT EXISTS terminals (id uuid PRIMARY KEY,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,branch_id uuid NOT NULL,name text NOT NULL,device_key text NOT NULL,active boolean NOT NULL)",
 "CREATE UNIQUE INDEX IF NOT EXISTS ix_terminals_device_key ON terminals(device_key)",
 "CREATE TABLE IF NOT EXISTS receipt_configurations (id uuid PRIMARY KEY,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,paper_width_mm integer NOT NULL,show_business_details boolean NOT NULL,show_customer boolean NOT NULL,show_cashier boolean NOT NULL,show_tax boolean NOT NULL,show_customer_balance boolean NOT NULL,show_powered_by boolean NOT NULL,auto_print_paid_sale boolean NOT NULL,credit_sale_print_mode text NOT NULL,payment_receipt_print_mode text NOT NULL,copies integer NOT NULL,footer text NOT NULL,receipt_prefix text NOT NULL,invoice_prefix text NOT NULL,payment_prefix text NOT NULL)"})await db.Database.ExecuteSqlRawAsync(statement);if(!await db.Staff.AnyAsync()){var admin=new StaffUser{Name="Admin",Role="Owner",PinHash=Security.HashPin(bootstrapPin)};db.Staff.Add(admin);db.AuditEvents.Add(new AuditEvent{StaffId=admin.Id,Actor=admin.Name,Action="Seeded",EntityType="System",Details="Created owner account",DeviceId="server"});await db.SaveChangesAsync();}if(!await db.Organizations.AnyAsync())db.Organizations.Add(new OrganizationProfile{Name="The BarCode",LegalName="",IndustryProfile="BarCafe",Currency="KES",Tagline="Smart business operations"});if(!await db.Branches.AnyAsync())db.Branches.Add(new Branch{Name="Main branch",Code="MAIN"});if(!await db.ReceiptConfigurations.AnyAsync())db.ReceiptConfigurations.Add(new ReceiptConfiguration());await db.SaveChangesAsync();await DemoData.Ensure(db);}
}
